/teleop_twist_joy_node:
  ros__parameters:
    axis_angular:
      pitch: -1
      roll: -1
      yaw: 0
    axis_linear:
      x: 1
      y: 0
      z: -1
    enable_button: 2
    enable_turbo_button: 5
    frame: teleop_twist_joy
    inverted_reverse: false
    publish_stamped_twist: false
    require_enable_button: true
    scale_linear:
      x: 0.0
      y: 0.0
      z: 0.0
    scale_angular:
      pitch: 0.0
      roll: 0.0
      yaw: 0.785

    scale_linear_turbo:
      x: 0.75
      y: 0.0 # IsaacSim launches robot from time to time when robot has transverse velocity, we will stick to forward and turning for now
      z: 0.0
    scale_angular_turbo:
      pitch: 0.0
      roll: 0.0
      yaw: 0.785


