<?xml version="1.0"?>
<robot name="antdrone" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="drone_name" default=""/>

  <xacro:include filename="$(find antdrone_description)/urdf/mecanum_properties.urdf.xacro" />
  <xacro:include filename="$(find antdrone_description)/urdf/base.urdf.xacro" />
  <xacro:include filename="$(find antdrone_description)/urdf/camera.urdf.xacro" />

  <xacro:property name="rs_height" value="${base_height/2 + 0.05}" />

  <xacro:camera drone_name="$(arg drone_name)" camera_pos="front" 
                x="0.410335" y="0" z="${rs_height}" 
                r_rs= "-1.57" p_rs="0" yaw_rs="-1.57" 
                r_cam="0" p_cam="0" yaw_cam="0"/>
  

  <xacro:camera drone_name="$(arg drone_name)" camera_pos="left" 
                x="0.0" y="0.247" z="${rs_height}" 
                r_rs="-1.57" p_rs="0.0" yaw_rs="0"
                r_cam="0" p_cam="0" yaw_cam="1.57"
  />

  <xacro:camera drone_name="$(arg drone_name)" camera_pos="rear" 
                x="-0.41" y="0.0" z="${rs_height}" 
                r_rs="-1.57" p_rs="0" yaw_rs="1.57" 
                r_cam="0" p_cam="0" yaw_cam="3.14"
  />

  <xacro:camera drone_name="$(arg drone_name)" camera_pos="right" 
                x="0" y="-0.247" z="${rs_height}" 
                r_rs="-1.57" p_rs="0" yaw_rs="3.14" 
                r_cam="0" p_cam="0" yaw_cam="-1.57"
  />
  
  <gazebo>
    <plugin name="mecanum_wheel_mimic" filename="libgazebo_ros_planar_move.so">
      <ros>
        <!-- The planar move plugin publishes each robot's odom -> base link transform in the ROS DOMAIN ID of gazebo,
          so each robot's odometry frame must be prepended by the robot's name. The prepended robot name is stripped out
          when the tf is bridged into the robots ROS domain ID.
         -->
        <namespace>$(arg drone_name)</namespace>
      </ros>
      <command_topic>cmd_vel</command_topic>
      <odometry_topic>odom</odometry_topic>
      <odometry_frame>$(arg drone_name)_odom</odometry_frame>
      <odometry_rate>15.0</odometry_rate>
      <robot_base_frame>$(arg drone_name)_base_link</robot_base_frame>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <update_rate>100</update_rate>
      <publish_rate>10</publish_rate>
    </plugin>
  </gazebo> 

  <xacro:base 
    drone_name="$(arg drone_name)"
    length="${base_length}" 
    width="${base_width}" 
    height="${base_height}" 
  />

</robot>