name: bridge_out_tf

topics:

  /front_rs_camera_info:
    type: sensor_msgs/msg/CameraInfo
    from_domain: 10
    to_domain: 8

  /rear_rs_camera_info:
    type: sensor_msgs/msg/CameraInfo
    from_domain: 10
    to_domain: 8

  /tf:
    type: tf2_msgs/msg/TFMessage
    from_domain: 10
    to_domain: 8

  /tf_static:
    type: tf2_msgs/msg/TFMessage
    from_domain: 10
    to_domain: 8