services:

  linorobot2-gz:
    container_name: linorobot2-gz
    build:
      context: .
      dockerfile: docker/linorobot2/dockerfiles/gz.dockerfile
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${DRONE0_DOMAIN_ID}
    volumes:
      - ./antdrone_gz:/home/humble_ws/src/antdrone_gz
      - ./antdrone_description:/home/humble_ws/src/antdrone_description
      - ./simulation/gazebo:/home/simulation/gazebo
      - ./simulation/models:/home/simulation/models
    working_dir: /home/humble_ws/
    network_mode: host
    ipc: host
    pid: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # alternatively, use `count: all` for all GPUs
              capabilities: [gpu]

  # linorobot2-nav:
  #   container_name: linorobot2-nav
  #   build:
  #     context: .
  #     dockerfile: docker/linorobot2/dockerfiles/nav.dockerfile
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     - DISPLAY=${DISPLAY}
  #   volumes:
  #     - ./antdrone_navigation:/home/humble_ws/src/antdrone_navigation
  #     - ./antdrone_localization:/home/humble_ws/src/antdrone_localization
  #     - ./yolo:/home/yolo
    
  #   # command: sleep infinity
  #   network_mode: host
  #   ipc: host
  #   pid: host

  

  # linorobot2-foxglove-bridge:
  #   container_name: linorobot2-foxglove-bridge
  #   build:
  #     context: .
  #     dockerfile: docker/linorobot2/dockerfiles/foxglove.dockerfile
  #   environment:
  #     - ROS_DOMAIN_ID=${DRONE0_DOMAIN_ID}
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #   command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml
  #   # command: sleep infinity
  #   network_mode: host
  #   ipc: host
  #   pid: host

  linorobot2-joytick:
    container_name: linorobot2-joystick
    build:
      context: .
      dockerfile: ./docker/linorobot2/dockerfiles/joystick.dockerfile
    tty: true
    stdin_open: true
    environment:
      - DRONE_ID=0
      - ROS_DOMAIN_ID=${DRONE0_DOMAIN_ID}
      - WHEELED_MOTION=false
    volumes:
      - ./antdrone_joystick:/home/humble_ws/src/antdrone_joystick:rw
      - ./antdrone_gz:/home/humble_ws/src/antdrone_gz
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    
  # linorobot2-pcl:
  #   container_name: linorobot2-pcl
  #   build:
  #     context: .
  #     dockerfile: ./docker/linorobot2/dockerfiles/pointcloud.dockerfile
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     - USE_SIM_TIME=True
  #     - NVIDIA_VISIBLE_DEVICES=all
  #     - ROS_DOMAIN_ID=${DRONE0_DOMAIN_ID}
  #   volumes:
  #     - ./antdrone_pcl:/home/humble_ws/src/antdrone_pcl:rw
  #     - ./antdrone_gz:/home/humble_ws/src/antdrone_gz:rw
  #     - ./perception_pcl:/home/humble_ws/src/perception_pcl
  #   network_mode: host
  #   ipc: host
  #   pid: host
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             capabilities: [gpu]
  #   runtime: nvidia
    
  # antdrone_depth_to_laserscan:
  #   container_name: antdrone-depth-to-laserscan
  #   build:
  #     context: .
  #     dockerfile: docker/linorobot2/dockerfiles/depth_to_laserscan.Dockerfile
  #   network_mode: host
  #   volumes:
  #     - ./antdrone_depth_to_laserscan:/home/humble_ws/src/antdrone_depth_to_laserscan
  #   environment:
  #     - DISPLAY=${DISPLAY}
  #     - NVIDIA_VISIBLE_DEVICES=all
  #     - ROS_DOMAIN_ID=${DRONE0_DOMAIN_ID}
  #   stdin_open: true
  #   tty: true
  #   ipc: host
  #   pid: host
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             capabilities: [gpu]
  #   runtime: nvidia

