services:

  linorobot2-yolo:
    container_name: linorobot2-yolo
    build:
      context: .
      dockerfile: docker/linorobot2/dockerfiles/yolo.dockerfile
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./antdrone_navigation/slam_images/:/home/slam_images
      - ./yolo:/home/yolo
    working_dir: /home/yolo
    command: sleep infinity
    network_mode: host
    ipc: host
    pid: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    runtime: nvidia

