/**/controller_server:
  ros__parameters:
    controller_frequency: 30.0
    controller_plugins:
    - FollowPath
    controller_server:
      verbose: false
    failure_tolerance: 0.0
    goal_checker:
      plugin: nav2_controller::SimpleGoalChecker
      stateful: true
      xy_goal_tolerance: 0.075
      yaw_goal_tolerance: 0.05
    goal_checker_plugins:
    - goal_checker

    min_theta_velocity_threshold: 0.0001
    min_x_velocity_threshold: 0.01
    min_y_velocity_threshold: 0.01
    
    odom_topic: odom
    
    progress_checker:
      movement_time_allowance: 10.0
      plugin: nav2_controller::SimpleProgressChecker
      required_movement_radius: 0.5

    progress_checker_plugin: progress_checker

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 56
      model_dt: 0.05
      batch_size: 1000
      vx_std: 0.2
      vy_std: 0.2
      wz_std: 0.4
      vx_max: 0.5
      vx_min: -0.35
      vy_max: 0.5
      wz_max: 1.9
      ax_max: 3.0
      ax_min: -3.0
      ay_max: 3.0
      az_max: 3.5
      iteration_count: 1
      prune_distance: 1.7
      transform_tolerance: 0.1
      temperature: 0.3
      gamma: 0.015
      motion_model: "Omni"
      visualize: true
      reset_period: 1.0 # (only in Humble)
      regenerate_noises: false
      TrajectoryVisualizer:
        trajectory_step: 25
        time_step: 3
      critics: ["ConstraintCritic", "CostCritic", "GoalCritic", "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic"]
      ConstraintCritic:
        enabled: false
        cost_power: 1
        cost_weight: 4.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.4
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 1.4
      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.4
      # ObstaclesCritic:
      #   enabled: true
      #   cost_power: 1
      #   repulsion_weight: 1.5
      #   critical_weight: 20.0
      #   consider_footprint: false
      #   collision_cost: 10000.0
      #   collision_margin_distance: 0.1
      #   near_goal_distance: 0.5
      #   inflation_radius: 0.55 # (only in Humble)
      #   cost_scaling_factor: 10.0 # (only in Humble)
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.81
        critical_cost: 300.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 0.5
        trajectory_point_step: 2
        inflation_layer_name: ""
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 14.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 1.4
        offset_from_furthest: 20
        use_path_orientations: true
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        offset_from_furthest: 4
        threshold_to_consider: 1.4
        max_angle_to_furthest: 1.0
        mode: 0
      # VelocityDeadbandCritic:
      #   enabled: true
      #   cost_power: 1
      #   cost_weight: 35.0
      #   deadband_velocities: [0.05, 0.05, 0.05]
      # TwirlingCritic:
      #   enabled: true
      #   twirling_cost_power: 1
      #   twirling_cost_weight: 10.0
      
      

/**/local_costmap/local_costmap:
  ros__parameters:

    footprint_padding: 0.15 # Larger footprint padding will make it hard to navigate to be close to the pipe rail fro dropoff
    footprint: "[ [0.41, 0.25], [-0.41, 0.25], [-0.41, -0.25], [0.41, -0.25] ]"

    # Larger costmap gives robot more heads up about incoming obstacles, but uses more computation. 
    # Since max pointcloud dist is 4m, set local costmap width and height to 2*4 = 8m to make most use of pointcloud.
    width: 8 
    height: 8

    update_frequency: 5.0
    publish_frequency: 5.0
    global_frame: map
    rolling_window: true
    resolution: 0.02  

    filters: ["keepout_filter", "inflation_layer"]
      
    keepout_filter:
      plugin: "nav2_costmap_2d::KeepoutFilter"
      enabled: True
      filter_info_topic: keepout_filter_info

    plugins: ["static_layer", "inflation_layer", "obstacle_layer"]

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: True
      observation_sources: scan
      footprint_clearing_enabled: False
      max_obstacle_height: 2.0
      combination_method: 1
      scan:
        topic: scan
        obstacle_max_range: 5.0
        obstacle_min_range: 0.0
        raytrace_max_range: 3.0
        raytrace_min_range: 0.0
        max_obstacle_height: 2.0
        min_obstacle_height: 0.0
        clearing: False
        marking: True
        data_type: "LaserScan"
        inf_is_valid: false
        # observation_persistence:  0.0

    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      footprint_clearing_enabled: False
      map_subscribe_transient_local: True
      enabled: true
      subscribe_to_updates: true
      transform_tolerance: 0.1

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: True
      inflation_radius: 0.5 # Larger inflation radius will make it hard to navigate to be close to the pipe rail fro dropoff
      cost_scaling_factor: 10.0
      inflate_unknown: false
      inflate_around_unknown: false

