# Parameter descriptions: https://docs.nav2.org/configuration/packages/configuring-map-server.html#configuring-map-server 
# Parameter values for keepout filter: https://docs.nav2.org/tutorials/docs/navigation2_with_keepout_filter.html

/costmap_filter_info_server:
  ros__parameters:
    type: 0
    base: 0.0
    multiplier: 1.0
    use_sim_time: true
    filter_info_topic: /keepout_filter_info
    mask_topic: /keepout_filter_mask

/filter_mask_server:
  ros__parameters:
    use_sim_time: true
    frame_id: "map"
    yaml_filename: "/home/humble_ws/src/linorobot2_navigation/maps/greenhouse_keepout.yaml"
    topic_name: /keepout_filter_mask

