# Parameter descriptions: https://docs.nav2.org/configuration/packages/configuring-map-server.html#configuring-map-server 
# Parameter values for keepout filter: https://docs.nav2.org/tutorials/docs/navigation2_with_keepout_filter.html

/costmap_filter_info_server:
  ros__parameters:
    type: 0
    filter_info_topic: "costmap_filter_info"
    mask_topic: "/global_costmap/keepout_filter_mask"
    base: 0.0
    multiplier: 1.0
    use_sim_time: true

/filter_mask_server:
  ros__parameters:
    use_sim_time: true
    frame_id: "map"
    topic_name: "/global_costmap/keepout_filter_mask"
    yaml_filename: "/home/humble_ws/src/linorobot2_navigation/maps/greenhouse.yaml"

