/nav2/planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_theta_star_planner/ThetaStarPlanner" # In Iron and older versions, "/" was used instead of "::"
      how_many_corners: 8
      w_euc_cost: 1.0
      w_traversal_cost: 2.0
      w_heuristic_cost: 1.0


/nav2/global_costmap:
  global_costmap:
    ros__parameters:
      footprint_padding: 0.0  # Extra padding around the footprint, added so planner only sends robot where it has space to move
      footprint: "[ [0.41, 0.25], [-0.41, 0.25], [-0.41, -0.25], [0.41, -0.25] ]"  # Full footprint dimensions of the robot

      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      resolution: 0.05

      filters: ["keepout_filter", "inflation_layer"]
      
      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"

      plugins: ["static_layer", "inflation_layer"]
      
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: true
        subscribe_to_updates: true
        transform_tolerance: 0.1
      
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.8  # Robot radius is 0.48m, planner plans with base link, so set to local costmap inflation radius + robot radius
        cost_scaling_factor: 2.0  # Higher cost scaling factor to heavily penalize keepout zones and obstacles
        inflate_unknown: false
        inflate_around_unknown: true

      

      always_send_full_costmap: True

      
