/**/planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_theta_star_planner/ThetaStarPlanner" # In Iron and older versions, "/" was used instead of "::"
      how_many_corners: 8
      w_euc_cost: 1.0
      w_traversal_cost: 2.0
      w_heuristic_cost: 1.0


/**/global_costmap:
  global_costmap:
    ros__parameters:
      footprint_padding: 0.15 # Larger footprint padding will make it hard to navigate to be close to the pipe rail fro dropoff
      footprint: "[ [0.41, 0.25], [-0.41, 0.25], [-0.41, -0.25], [0.41, -0.25] ]"  # Full footprint dimensions of the robot

      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      
      resolution: 0.02

      filters: ["keepout_filter", "inflation_layer"]
      

      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: keepout_filter_info

      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: true
        subscribe_to_updates: true
        transform_tolerance: 1.0

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        footprint_clearing_enabled: true
        max_obstacle_height: 2.0
        combination_method: 1
        scan:
          topic: scan
          obstacle_max_range: 5.0
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          inf_is_valid: false
      
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: True
        inflation_radius: 0.55  # Robot radius is 0.48m, planner plans with base link, so set to local costmap inflation radius + robot radius
        cost_scaling_factor: 10.0  # Higher cost scaling factor to heavily penalize keepout zones and obstacles
        inflate_unknown: False
        inflate_around_unknown: True

      

      always_send_full_costmap: True

      
