/nav2/planner_server:
  ros__parameters:
    GridBased:
      allow_unknown: true
      plugin: nav2_navfn_planner/NavfnPlanner
      tolerance: 0.5
      use_astar: false
      use_final_approach_orientation: false
    expected_planner_frequency: 1.0
    planner_plugins:
    - GridBased


/nav2/global_costmap:
  global_costmap:
    ros__parameters:
      footprint_padding: 0.05
      footprint: "[ [0.41, 0.25], [-0.41, 0.25], [-0.41, -0.25], [0.41, -0.25] ]"

      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      resolution: 0.05
      plugins: ["static_layer", "inflation_layer"]
      
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: true
        subscribe_to_updates: true
        transform_tolerance: 0.1
      
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.25
        cost_scaling_factor: 1.0
        inflate_unknown: false
        inflate_around_unknown: true

      always_send_full_costmap: True
      
