<?xml version="1.0"?>
<robot name="linorobot2" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="namespace" default=""/>

  <xacro:include filename="$(find linorobot2_description)/urdf/mecanum_properties.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/mech/base.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/mech/mecanum_wheel_left_fixed.urdf.xacro" />

  <xacro:include filename="$(find linorobot2_description)/urdf/mech/end_channel.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/mech/side_channel.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/robots/camera.urdf.xacro" />

  <xacro:property name="rs_height" value="${base_height/2 + 0.05}" />

  <xacro:camera namespace="$(arg namespace)" camera_pos="front" 
                x="0.410335" y="0" z="${rs_height}" 
                r_rs= "-1.57" p_rs="0" yaw_rs="-1.57" 
                r_cam="0" p_cam="0" yaw_cam="0"/>
  

  <xacro:camera namespace="$(arg namespace)" camera_pos="left" 
                x="0.0" y="0.247" z="${rs_height}" 
                r_rs="-1.57" p_rs="0.0" yaw_rs="0"
                r_cam="0" p_cam="0" yaw_cam="1.57"
  />

  <xacro:camera namespace="$(arg namespace)" camera_pos="rear" 
                x="-0.41" y="0.0" z="${rs_height}" 
                r_rs="-1.57" p_rs="0" yaw_rs="1.57" 
                r_cam="0" p_cam="0" yaw_cam="3.14"
  />

  <xacro:camera namespace="$(arg namespace)" camera_pos="right" 
                x="0" y="-0.247" z="${rs_height}" 
                r_rs="-1.57" p_rs="0" yaw_rs="3.14" 
                r_cam="0" p_cam="0" yaw_cam="-1.57"
  />
  
  <gazebo>
    <plugin name="mecanum_wheel_mimic" filename="libgazebo_ros_planar_move.so">
      <ros>
        <namespace>$(arg namespace)</namespace>
        <remapping>odom:=odom_unscaled</remapping>
        <remapping>cmd_vel:=cmd_vel_scaled</remapping>
      </ros>
      <command_topic>cmd_vel</command_topic>
      <odometry_topic>odom</odometry_topic>
      <odometry_frame>$(arg namespace)_odom</odometry_frame>
      <odometry_rate>15.0</odometry_rate>
      <robot_base_frame>$(arg namespace)_base_link</robot_base_frame>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>false</publish_odom_tf>
      <update_rate>100</update_rate>
      <publish_rate>10</publish_rate>
    </plugin>
  </gazebo> 

  <xacro:base 
    namespace="$(arg namespace)"
    length="${base_length}" 
    width="${base_width}" 
    height="${base_height}" 
  />

  <!-- Sliding platform link -->
  <link name="$(arg namespace)_sliding_platform">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} 0.05"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} 0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/> <!-- Small, non-zero mass -->
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <!-- Prismatic joint for vertical sliding -->
  <joint name="$(arg namespace)_sliding_joint" type="prismatic">
    <parent link="$(arg namespace)_base_link"/>
    <child link="$(arg namespace)_sliding_platform"/>
    <origin xyz="0 0 ${base_height/2+0.05}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="0" upper="0.5" effort="100" velocity="0.5"/>
  </joint>

  <gazebo>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <ros>
        <namespace>$(arg namespace)</namespace>
        <remapping>joint_states:=joint_states</remapping>
      </ros>
      <update_rate>30</update_rate>
      <joint_name>$(arg namespace)_sliding_joint</joint_name>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="gazebo_ros_joint_pose_trajectory"
        filename="libgazebo_ros_joint_pose_trajectory.so">
        <ros>
          <!-- <namespace>$(arg namespace)</namespace> -->
        </ros>
        <update_rate>20</update_rate>
        <frame_id>drone_boris_base_link</frame_id>
        <!-- <joint_name>$(arg namespace)_sliding_joint</joint_name> -->
    </plugin>
  </gazebo>






</robot>