/amcl:
  ros__parameters:
    base_frame_id: base_link
    odom_frame_id: odom
    # See what alpha params do for omni motion model: https://github.com/ros-navigation/navigation2/blob/f3ef5d4c18056f7e7715025d0e3a843c42258554/nav2_amcl/src/motion_model/omni_motion_model.cpp#L34
    alpha1: 0.05 # Rotation is quite accurate but not perfect.
    alpha2: 0.05 # Transverse movement doesnt cause much rotation at all
    alpha3: 0.05 # Transverse movement is quite accurate but not perfect.
    alpha4: 0.0 # Assume for now that rotating does not cause any strafing or transverse movement.
    alpha5: 0.2 # Strafing is very noisy.
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: map
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: -1.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 720
    max_particles: 2000
    min_particles: 500
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::OmniMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.005
    scan_topic: /scan


    
