/behavior_server:
  ros__parameters:
    /bond_disable_heartbeat_timeout: true
    behavior_plugins: ["spin", "backup",  "wait"] # "drive_on_heading", "assisted_teleop",

    costmap_topic: local_costmap/costmap_raw
    cycle_frequency: 10.0
    footprint_topic: local_costmap/published_footprint
    global_frame: map
    robot_base_frame: base_link
    simulate_ahead_time: 2.0
    transform_tolerance: 0.1
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    # drive_on_heading:
    #   plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    # assisted_teleop:
    #   plugin: "nav2_behaviors/AssistedTeleop"

    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2
    

