/costmap_filter_info_server:
  ros__parameters:
    type: 0
    base: 0.0
    multiplier: 1.0
    filter_info_topic: /keepout_filter_info
    mask_topic: /keepout_filter_mask

/filter_mask_server:
  ros__parameters:
    frame_id: "map"
    topic_name: /keepout_filter_mask

