# Nav spawn is descriptive - it is the robots understanding of its placement in a nav2 map.

greenhouse:
  drone_boris:
    x0: 16.5
    y0: -19.0
    z0: 0.15
    yaw0: 0.0

lab:
  drone_boris:
    x0: 6.25
    y0: -1.1
    z0: 0.3
    yaw0: 0.0


physical_lab_2:
  drone_boris:
    x0: -1.0
    y0: -1.0
    z0: -1.0
    yaw0: -1.0