# Cropping is in realsense frame, where:
# positive y is facing down (with gravity)
# positive z is facing out toward the object in view
# positive x is facing left (when viewing camera from its rear)

/**: # Apply same settings to all crop nodes that use this config file.
  ros__parameters:
    approximate_sync: false
    keep_organized: false
    max_queue_size: 3
    
    max_x: 5.0 # Set max_x large enough to cover view in front of robot
    min_x: -5.0 # Set max_x large enough to cover view in front of robot

    max_y: 0.16 # Set max_y low enough to remove floor, but high enough to still include pipe rails. 
    min_y: -0.5 # Set min_y low enough to see all of worker

    max_z: 4.0 # Physical realsense starts to get noisy past 4m.
    min_z: 0.0 # Included closest possible points to camera.

    negative: false
    transient_local_indices: false
    filter_limit_negative: false
    use_indices: false