# Downsampling is in base_link frame on an already-cropped pointcloud
# Base link orientation:
# positive x points toward front of robot
# positive y points to robot's left
# positive z faces up against gravity

/**: # Apply same params to all downsample nodes that use this config file
  ros__parameters:
    approximate_sync: false
    filter_limit_negative: true
    leaf_size: 0.01
    max_queue_size: 3
    min_points_per_voxel: 1
    transient_local_indices: false
    use_indices: false
    qos_overrides:
      /clock:
        subscription:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: best_effort
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable

