# Downsampling is in base_link frame on an already-cropped pointcloud
# Base link orientation:
# positive x points toward front of robot
# positive y points to robot's left
# positive z faces up against gravity

/**: # Apply same params to all downsample nodes that use this config file
  ros__parameters:

    # Incoming pointcloud is already cropped.
    # Be sure to set filter_limit_max and filter_limit_min to not apply a second cropping.
    filter_field_name: z
    filter_limit_max: 3.0
    filter_limit_min: -1.0
    filter_limit_negative: false
    
    leaf_size: 0.01
    max_queue_size: 3
    min_points_per_voxel: 1
    transient_local_indices: false
    use_indices: false
