# PCLs are in base_link frame when downsampled, and are already cropped.
# So, filter z is basically pointless, just set it to be large enough that no points are removed.

/**/front_rs_pointcloud_downsampler:
  ros__parameters:
    # Realsense d435 simple tech specs: https://www.intelrealsense.com/depth-camera-d435i/
    # Filter field is unused for this filter, cropping is done by dedicated crop filter.
    filter_field_name: z
    filter_limit_max: 3.0
    filter_limit_min: 0.0
    filter_limit_negative: false
    leaf_size: 0.01
    max_queue_size: 3
    min_points_per_voxel: 1
    transient_local_indices: false
    use_indices: false

/**/rear_rs_pointcloud_downsampler:
  ros__parameters:
    # Realsense d435 simple tech specs: https://www.intelrealsense.com/depth-camera-d435i/
    # Filter field is unused for this filter, cropping is done by dedicated crop filter.
    filter_field_name: z
    filter_limit_max: 3.0
    filter_limit_min: 0.0
    filter_limit_negative: false
    leaf_size: 0.01
    max_queue_size: 3
    min_points_per_voxel: 1
    transient_local_indices: false
    use_indices: false

/**/left_rs_pointcloud_downsampler:
  ros__parameters:
    # Realsense d435 simple tech specs: https://www.intelrealsense.com/depth-camera-d435i/
    # Filter field is unused for this filter, cropping is done by dedicated crop filter.
    filter_field_name: z
    filter_limit_max: 3.0
    filter_limit_min: 0.0
    filter_limit_negative: false
    leaf_size: 0.01
    max_queue_size: 3
    min_points_per_voxel: 1
    transient_local_indices: false
    use_indices: false

/**/right_rs_pointcloud_downsampler:
  ros__parameters:
    # Realsense d435 simple tech specs: https://www.intelrealsense.com/depth-camera-d435i/
    # Filter field is unused for this filter, cropping is done by dedicated crop filter.
    filter_field_name: z
    filter_limit_max: 3.0
    filter_limit_min: 0.0
    filter_limit_negative: false
    leaf_size: 0.01
    max_queue_size: 3
    min_points_per_voxel: 1
    transient_local_indices: false
    use_indices: false
