/rear_rs_pointcloud_cropper:
  ros__parameters:
    approximate_sync: false
    keep_organized: false
    max_queue_size: 3
    max_x: 0.55
    max_y: 0.2 # max_y needs to filter out the rails themselves
    max_z: 1.0
    
    min_x: -0.55
    min_y: -0.0 # Weird artifacts appearing above the robot off shop floor's wall, -0.3 is enough clearance to get robot chassis past any obstacles
    min_z: 0.0
    min_points_per_voxel: 2
    negative: false
    transient_local_indices: false
    filter_limit_negative: false
    use_indices: false
