<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="base" params="length width height mass wheel_radius wheel_pos_z">
    <link name="base_footprint2"/>
    
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0"/>
        <inertia ixx="0"  ixy="0"  ixz="0" iyy="0" iyz="0" izz="0" />
      </inertial>
    </link>

    <joint name="base_to_footprint" type="fixed">
      <parent link="base_footprint2"/>
      <child link="base_link"/>
      <origin xyz="0 0 ${wheel_radius - wheel_pos_z}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
</robot>