apriltag:                 # node name
  ros__parameters:
    # setup (defaults)
    image_transport: compressed  # image format: "raw" or "compressed"
    family: 16h5         # tag family name: 16h5, 25h9, 36h11
    size: 0.106 #0.136             # Beware - tags included from https://github.com/koide3/gazebo_apriltag/tree/master have a white border, so the tag size is smaller than the image size.
    profile: false        # print profiling information to stdout

    # tuning of detection (defaults)
    max_hamming: 1        # maximum allowed hamming distance (corrected bits)
    detector:
      threads: 3          # number of threads
      decimate: 0.0       # decimate resolution for quad detection
      blur: 0.0           # sigma of Gaussian blur for quad detection
      refine: True           # snap to strong gradients
      sharpening: 1.0    # sharpening of decoded images
      debug: false            # write additional debugging images to current working directory

    # (optional) list of tags
    # If defined, 'frames' and 'sizes' must have the same length as 'ids'.
    tag:
      ids:    [0,1,2,3,4,5]         # tag IDs for which to publish transform
      frames: [tag16h5:0, tag16h5:1, tag16h5:2, tag16h5:3, tag16h5:4, tag16h5:5]   # frame names
      sizes:  [0.106, 0.106, 0.106, 0.106, 0.106, 0.106]     # tag-specific edge size, overrides the default 'size'