image_width: 800
image_height: 600
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [560.60033,   0.     , 427.78192,
           0.     , 560.20102, 301.07989,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.009904, -0.008212, -0.004577, -0.000848, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [556.4679 ,   0.     , 427.03928,   0.     ,
           0.     , 557.27911, 298.34404,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
