/front_rs_pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.00872664625
    angle_max: 0.785
    angle_min: -0.785
    inf_epsilon: 1.0
    max_height: 1.5
    min_height: -1.0
    queue_size: 11
    range_max: 5.0
    range_min: 0.0
    scan_time: 0.03333333333333333
    target_frame: 'base_link' # Transforming to target frame base_link puts scan in correct frame. Keeping it in original frame gets really messed up. Not sure why.
    transform_tolerance: 1.0
    use_inf: false
    use_sim_time: true

/left_rs_pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.00872664625
    angle_min: 0.785
    angle_max: 2.355
    inf_epsilon: 1.0
    max_height: 1.5
    min_height: -1.0
    queue_size: 11
    range_max: 5.0
    range_min: 0.0
    scan_time: 0.03333333333333333
    target_frame: 'base_link' # Transforming to target frame base_link puts scan in correct frame. Keeping it in original frame gets really messed up. Not sure why.
    transform_tolerance: 1.0
    use_inf: false
    use_sim_time: true


/rear_rs_left_pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.00872664625
    angle_min: 2.355
    angle_max: 3.14  
    inf_epsilon: 1.0
    max_height: 1.5
    min_height: -1.0
    queue_size: 11
    range_max: 5.0
    range_min: 0.0
    scan_time: 0.03333333333333333
    target_frame: 'base_link' # Transforming to target frame base_link puts scan in correct frame. Keeping it in original frame gets really messed up. Not sure why.
    transform_tolerance: 1.0
    use_inf: false
    use_sim_time: true

/rear_rs_right_pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.00872664625
    angle_min: -3.14
    angle_max: -2.355
    inf_epsilon: 1.0
    max_height: 1.5
    min_height: -1.0
    queue_size: 11
    range_max: 5.0
    range_min: 0.0
    scan_time: 0.03333333333333333
    target_frame: 'base_link' # Transforming to target frame base_link puts scan in correct frame. Keeping it in original frame gets really messed up. Not sure why.
    transform_tolerance: 1.0
    use_inf: false
    use_sim_time: true

/right_rs_pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.00872664625
    angle_max: -0.785
    angle_min: -2.355
    inf_epsilon: 1.0
    max_height: 1.5
    min_height: -1.0
    queue_size: 11
    range_max: 5.0
    range_min: 0.0
    scan_time: 0.03333333333333333
    target_frame: 'base_link' # Transforming to target frame base_link puts scan in correct frame. Keeping it in original frame gets really messed up. Not sure why.
    transform_tolerance: 1.0
    use_inf: false
    use_sim_time: true
