/rear_rs_pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.0017453292519943295
    angle_max: 3.141592653589793
    angle_min: -3.141592653589793
    inf_epsilon: 1.0
    max_height: 1.5
    min_height: 0.0
    queue_size: 11
    range_max: 5.0
    range_min: 0.0
    scan_time: 0.03333333333333333
    target_frame: 'base_link' # Transforming to target frame base_link puts scan in correct frame. Keeping it in original frame gets really messed up. Not sure why.
    transform_tolerance: 0.01
    use_inf: true
    use_sim_time: false
